# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00bfd9545463c377e9a0ed3941cc698a2220562f47054a154ae9eeb6fa759a4681f6e1948f34ed3cd416cd282b4111d8ffbb57bc91a63a1ad35f514816e69886

test:
  secret_key_base: b9d03de3f1f43a0a338f250ad83f62b70a74061fc513e32b92b209b535e368a6d665c85d3189365fa1f58d5e1611ce6cd48776ab7a58ff2ba9e3e560bb41eb26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
